export const AllCollection = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBed%20Scarf%2FMenagerie%2Fimage-thumb__51143__header_fullscreen_2x_jpg%2F6934-MO-Menagerie-of-Extinct-Animals-Raven-XL-Scarf.webp&w=2048&q=80",
    alt: "Menagerie of Exact Animal bed ScarfXL",
    title: "Menagerie of Exact Animal bed ScarfXL",
    price: "$250",
    available: "In stock",
    category: "bedding",
    brandName: "Our Collection",
    type: "AllCollection",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FBedspread%2FDodo%20Pavone%2Fimage-thumb__51138__header_fullscreen_2x_jpg%2F6933-MO-Dodo-Pavone-Bedspread-Ivory.webp&w=2048&q=80",
    title: "Embroidered Dodo Pavone Bedspread",
    price: "$381",
    available: "only 2 left in stock",
    brandName: "Our Collection",
    type: "AllCollection",
    category: "Bath",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBedding%2FDuvets%2FDuvets-colored-sheets%2Fimage-thumb__56613__header_fullscreen_2x_jpg%2FUmbrella-Squid_Silver_2P-10_Topshot-NEW_1.webp&w=2048&q=80",
    title: "Umbrella Squid Duvet Cover Set",
    price: "$250",
    available: "In stock",
    brandName: "Our Collection",
    type: "AllCollection",
    category: "bedding",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBath%2FTowel%2Fimage-thumb__65444__header_fullscreen_2x_jpg%2FDodo-Pavone-Towel_Stack-Topshot.webp&w=1080&q=80",
    title: "Dodo Pavone Towel",
    price: "$20",
    available: "In stock",
    brandName: "Our Collection",
    type: "AllCollection",
    category: "bedding",
  },
];
