export const furniture = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FContainer%2FContainer%20Bodhi%2F3401%2Fimage-thumb__3401__header_fullscreen_2x_jpg%2FContainer-Table_Bodhi-212-final.webp&w=3840&q=80",
    alt: "Container table by marchel wanders",
    title: "Container Table by Marchel Wanders",
    price: "$1845",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FKisss%20Lounge%20Chair%2FPhotography%2FProduct%20Images%2FSingle%20Chair%20-%20Diving-3-623%2FPNG%2F83947%2Fimage-thumb__83947__header_fullscreen_2x_jpg%2FKisss-Chair-Divina-3-623_Product-SingleChair-1.webp&w=1200&q=80",
    title: "Kiss Lounge Chair by Marchel Wanders",
    price: "$2750",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHana%20Chair%20Dining%2FUn-Upholstered%2FTerracotta%2FPhotography%2FPng%20-%20Transparent%2F71844%2Fimage-thumb__71844__header_fullscreen_2x_jpg%2FTERRACOTA-HANA-CHAIR-BLACK_LEGS-FRONT.webp&w=1080&q=80",
    alt: "Hana Chairs Un-Upholstered set of 2 By Simone",
    title: "Hana Chairs Un-Upholstered set of 2 By Simone",
    price: "$590",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FKnitty%20Lounge%20Chair%2F67784%2Fimage-thumb__67784__header_fullscreen_2x_jpg%2FKnitty-Lounge-Chair-front-angle-Mosaic-2-0222%20background.webp&w=750&q=80",
    title: "Knitty Lounge Chair by Nika",
    price: "$6550",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHana%20Chair%20Dining%2FUpholstered%2FPhotography%2FPNG%2F73529%2Fimage-thumb__73529__header_fullscreen_2x_jpg%2FHana-Chair-Upholstered-product-32.webp&w=1080&q=80",
    title: "Hana Chairs Upholstered by Simone ",
    price: "$748",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Vis%20a%20Vis%2FProduct%20Photography%2F75276%2Fimage-thumb__75276__header_fullscreen_2x_jpg%2FAldora_Vis_a_Vis_Leather_Front_Left.webp&w=3840&q=80",
    title: "Aldora Vis a Vis by Cristina Celestino",
    price: "$3500",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNo%20Screw%20No%20Glue%2FNo%20Screw%20No%20Glue%20Buffet%2Fimage-thumb__37899__header_fullscreen_2x_jpg%2FNo-Screw-No-Glue-Buffet-Mobile-parts-04.jpg&w=3840&q=80",
    title: "No Screw No Glue Buffet by Joost Van",
    price: "$4324",
    available: "Only 2 left in stock",
    type: "furniture",
    category: "Storage",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNo%20Screw%20No%20Glue%2FNo%20Screw%20No%20Glue%20Cabinet%2Fimage-thumb__40213__header_fullscreen_2x_jpg%2FNo-Screw-No-Glue-Cabinet-Front.jpg&w=1080&q=80",
    title: "No Screw No Glue Buffet by Joost Van",
    price: "$5479",
    available: "In stock",
    type: "furniture",
    category: "Storage",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FContainer%2FContainer%20NEW%2FContainer%20Table%20Classic%2Fimage-thumb__39064__header_fullscreen_2x_jpg%2FContainer-Table-Classic-Black.jpg&w=3840&q=80",
    title: "Container Table Classic by Marcel Wanders",
    price: "$1854",
    available: "In stock",
    type: "furniture",
    category: "Tables",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FSmoke%20Series%2FSmoke%20Armchair%2F13028%2Fimage-thumb__13028__header_fullscreen_2x_jpg%2FSmoke-Armchair-Transparent.webp&w=1080&q=80",
    title: "Smoke Armchair by Maarten Bas",
    price: "$5474",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FSmoke%20Series%2FSmoke%20Dining%20chair%2F950%2Fimage-thumb__950__header_fullscreen_2x_jpg%2Fsmokedining-s-transparent.webp&w=1080&q=80",
    title: "Smoke Dinning Chair by Maarten Bas",
    price: "$2176",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Chaise%20Longue%2FProduct%20Photography%20(old)%2F75521%2Fimage-thumb__75521__header_fullscreen_2x_jpg%2FAldora_sofa_chaise_longue_left_palette_product_front.webp&w=3840&q=80",
    title: "Aldora Chaise Lounge by Cristina",
    price: "$2900",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAldora%2FAldora%20Sofa%2FProduct%20Photography%2F75226%2Fimage-thumb__75226__header_fullscreen_2x_jpg%2FAldora_Sofa_DODO_Front.webp&w=3840&q=80",
    title: "Aldora Sofa by Cristina",
    price: "$3500",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FAmami%2FAmami%20Sofa%2F1285%2Fimage-thumb__1285__header_fullscreen_2x_jpg%2FAmami-Sofa-Brown.webp&w=3840&q=80",
    title: "Amami by Lorenza Bozzoli",
    price: "$11860",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FBart%2FBart%20Swivel%2F37404%2Fimage-thumb__37404__header_fullscreen_2x_jpg%2FBart-Swivel-Blushing-Sloth-Wooly.webp&w=1080&q=80",
    title: "Bart Armchair by Moooi",
    price: "$4082",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarbon%2FCarbon%20Barstool%2FCarbon%20Barstool%20Low%2F1484%2Fimage-thumb__1484__header_fullscreen_2x_jpg%2FCarbon-Bar-Stool-Black-Front.webp&w=1080&q=80",
    title: "Carbon Bar Stool by Bertjan Port",
    price: " from $1096",
    available: "In stock",
    type: "furniture",
    category: "Storage",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Buffet%2Fimage-thumb__15622__header_fullscreen_2x_jpg%2Fzio_buffet_cinnamon-drawer-open.webp&w=3840&q=80",
    title: "Pig Table by Front",
    price: "$2911",
    available: "In stock",
    type: "furniture",
    category: "Storage",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FShift%2FShift%20Dining%20Chair%2F1924%2Fimage-thumb__1924__header_fullscreen_2x_jpg%2FShift-Dining-Chair-Grey-Blue-1.webp&w=1080&q=80",
    title: "Shift Dinning Chair by Jonas Forsman",
    price: "$701",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FShift%2FShift%20Lounge%20Chair%2F1917%2Fimage-thumb__1917__header_fullscreen_2x_jpg%2FShift-Lounge-Chair-bluegrey-2.webp&w=1080&q=80",
    title: "Shift Lounge Chair by Jonas Forsman",
    price: "$1126",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FThe%20Golden%20Chair%2Fimage-thumb__1639__header_fullscreen_2x_jpg%2Fgolden-chair-front.webp&w=1080&q=80",
    title: "The Golden Chair by Nika Zupanc",
    price: "$1184",
    available: "In stock",
    type: "furniture",
    category: "Seating",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Dining%20Table%2FZio%20Dining%20Table%20310%2Fimage-thumb__4046__header_fullscreen_2x_jpg%2FZio-Table-Composition-310-2.webp&w=3840&q=80",
    title: "Zoi Footstool by Marchel Wandars",
    price: "$835",
    available: "In stock",
    type: "furniture",
    category: "Tables",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPooof%2FPooof%2070%2Fimage-thumb__37414__header_fullscreen_2x_jpg%2FPooof-70-Menagerie-of-Extinct-Animals-Aristo-Quagga.webp&w=1080&q=80",
    title: "Proof by Moooi",
    price: "$1002",
    available: "In stock",
    type: "furniture",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FZio%2FZio%20Coffee%20Table%2FZio%20Coffee%20Table%20110%2Fimage-thumb__1992__header_fullscreen_2x_jpg%2FZio-Coffee-Table-Front-1.webp&w=3840&q=80",
    title: "Zoi Coffee Table by Marchel Wandars",
    price: "$3361",
    available: "In stock",
    type: "furniture",
  },
];
export let furnitureHead = {
  name: "Furniture",
  Btn: ["All Furnitures", "Seating", "Storage", "Tables"],
};
