export const wallFloor = [
  // {
  //   src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fumbrella%20squid%2FQueen%20Cobra%2Fimage-thumb__46568__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_QueenCobra_MO4012_Mood_Web_HR.webp&w=3840&q=80",
  //   alt: "Queen Cobra Wallcovering",
  //   title: "Queen Cobra Wallcovering",
  //   price: "$249",
  //   available: "In stock",
  //   type: "wallFloor",
  // },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FLinesLinesLines%2FProduct%20Shots%2F81972%2Fimage-thumb__81972__header_fullscreen_2x_jpg%2FMoooi-Carpets-LinesLinesLines-By-Alf-Product_1.webp&w=1080&q=80",
    title: "LinesLinesLines Carpet",
    price: "$2739",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2FLiquid%20Layers%20Carpet%20Collection%2Fimage-thumb__31419__header_fullscreen_2x_jpg%2FMarl-250.webp&w=3840&q=80",
    alt: "Liquid Layers Carpet",
    title: "Liquid Layers Carpet",
    price: "$2441",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FHerbarium%20of%20Extinct%20Plants%2Fimage-thumb__34159__header_fullscreen_2x_jpg%2FHerbarium-of-Extinct-Plants-250.webp&w=3840&q=80",
    title: "Herbarium of Extinct Plants Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FBisanto%2Fimage-thumb__36884__header_fullscreen_2x_jpg%2FADRIANO-Carpet.jpg&w=1080&q=80",
    title: "Bisanto Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FFlowergarden%2Fimage-thumb__40518__header_fullscreen_2x_jpg%2FFlower-Garden-Night.webp&w=1080&q=80",
    title: "Flowergarden Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FSprouts%2Fimage-thumb__26502__header_fullscreen_2x_jpg%2FSprouts-Carpet.webp&w=1080&q=80",
    title: "Sprouts Carpet",
    price: "$2750",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FIn%20The%20Meadow%2Fimage-thumb__37764__header_fullscreen_2x_jpg%2FEmbryo-II-200x264-300DPI.jpg&w=1080&q=80",
    title: "In the Meadow Carpet",
    price: "$2549",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14285%2Fimage-thumb__14285__header_fullscreen_2x_jpg%2FMaze%20Puglia-Design-190042.webp&w=3840&q=80",
    title: "Maze Carpet",
    price: "$2600",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14209%2Fimage-thumb__14209__header_fullscreen_2x_jpg%2FCrystal%20Brown-Design-190003.webp&w=1080&q=80",
    title: "Crystal Carpet",
    price: "$2880",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2Fimage-thumb__14333__header_fullscreen_2x_jpg%2FUrbanMandalas_Mexico_250cm_S170009.webp&w=3840&q=80",
    title: "Urban Mandalas Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2Fimage-thumb__14276__header_fullscreen_2x_jpg%2FMalmaison_Aquamarine_160043_160047.webp&w=3840&q=80",
    title: "Malmaison Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fmemento%20moooi%20medley%2Fimage-thumb__46683__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_MementoMoooiMedley_MO4032_Mood_Web_HR.webp&w=3840&q=80",
    title: "Memento Moooi Medley Wallcovering",
    price: "$159",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fdandelion%20cranes%2Fimage-thumb__46658__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_DandelionCranes_MO4021_Mood_Web_HR.webp&w=3840&q=80",
    title: "Dandelion Cranes Wallcovering",
    price: "$189",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fpogo%20goat%2Fimage-thumb__46593__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_PogoGoat_MO4052_Mood_Web_HR.webp&w=3840&q=80",
    title: "Pogo Goat Wallcovering",
    price: "$299",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fgolden%20tiger%2Fimage-thumb__47393__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_DandelionCranes_MO4022_2_Mood_Web_HR-2-3.webp&w=3840&q=80",
    title: "Golden Tiger Wallcovering",
    price: "$169",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Fmimic%20moth%2Fimage-thumb__46598__header_fullscreen_2x_jpg%2FMoooiWallcoveringMementoMoooi_MimicMoth_MO4000_3_Mood_Web_HR.webp&w=3840&q=80",
    title: "Mimic Moth Wallcovering",
    price: "$299",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMemento%20Moooi%20Medley%2Fimage-thumb__47858__header_fullscreen_2x_jpg%2FMemento-Moooi-Medley-Dawn-250.webp&w=1080&q=80",
    title: "Memento Moooi Medley Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Ftokyo%20blue%2Fshojiblossom%2Fimage-thumb__47468__header_fullscreen_2x_jpg%2Fmoooiwallcoveringtokyoblue-shojiblossom-mo3030-m2-V2.webp&w=3840&q=80",
    title: "Shoji Blossom Wallcovering",
    price: "$369",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FRe-Cut%20Tiger%20from%20Tibet%2Fimage-thumb__40678__header_fullscreen_2x_jpg%2FTiger-from-Tibet-300DPI.webp&w=1080&q=80",
    title: "iger from Tibet",
    price: "$2399",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDonut%20Carpet%2FHeart%2Fimage-thumb__49733__header_fullscreen_2x_jpg%2FHeart-Donut.webp&w=1080&q=80",
    title: "Donut Fear Carpet",
    price: "$2910",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FSand%2Fimage-thumb__52268__header_fullscreen_2x_jpg%2FChemistry-Morning-Dunes-300x400-300DPI.webp&w=1080&q=80",
    title: "Sand Carpet",
    price: "$2560",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FSerpentine%2Fimage-thumb__52278__header_fullscreen_2x_jpg%2FMoooi_SerpentineCarpet_GreenYellow_20220404-300DPI.webp&w=1080&q=80",
    title: "Serpentine Carpet",
    price: "$3030",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FAkira%2Fimage-thumb__52263__header_fullscreen_2x_jpg%2FAkira-Vermilion-kit-miles-carpet.webp&w=1080&q=80",
    title: "Akira Carpet",
    price: "$2600",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FWallcovering%2Ftokyo%20blue%2Frendezvoustokyoblue%2Fimage-thumb__17212__header_fullscreen_2x_jpg%2Fmoooiwallcoveringtokyoblue-rendezvoustokyoblue-mo3010-m2.webp&w=3840&q=80",
    title: "Rendezvous Tokyo Blue Wallcovering",
    price: "$159",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FRendezvous-Tokyo-Blue%2Fimage-thumb__24598__header_fullscreen_2x_jpg%2FRendezvous-indigo-200x300-300dpi.webp&w=1080&q=80",
    title: "Rendezvous Tokyo Blue Carpet",
    price: "$2600",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMooon%20Carpet%2Fimage-thumb__58283__header_fullscreen_2x_jpg%2FMooon-carpet-no-background.webp&w=1080&q=80",
    title: "Mooon Carpet",
    price: "$3150",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FTulip%2Fimage-thumb__59983__header_fullscreen_2x_jpg%2FTulip%20Mania%20Red%20Shell%20300Dpi.webp&w=1080&q=80",
    title: "Tulip Mania Carpet",
    price: "$2430",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FMixing%20Pixels%2Fimage-thumb__61749__header_fullscreen_2x_jpg%2FMixing-Pixels-of-Scribble-I-300Dpi.webp&w=1080&q=80",
    title: "Mixing Pixels Carpet",
    price: "$2739",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FExtinct%20Animals%20Carpet%2Fimage-thumb__62794__header_fullscreen_2x_jpg%2FQueen-Cobra.webp&w=1080&q=80",
    title: "Extinct Animals Carpet",
    price: "$74",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FForest%20Floors%2Fimage-thumb__60723__header_fullscreen_2x_jpg%2FForrest-Floors-Landscape.webp&w=3840&q=80",
    title: "Forest Floors Carpet",
    price: "$2600",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FPollination%20of%20Hortensia%2Fimage-thumb__64764__header_fullscreen_2x_jpg%2FPOLLINATION-OF-HORTENSIA-CARPET-SPRING-200x300cm-300Dpi.webp&w=1080&q=80",
    title: "Pollination of Hortensia Carpet",
    price: "$2600",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FColour%20Dial%2Fimage-thumb__64959__header_fullscreen_2x_jpg%2FColourDial-Arc-Iridescence-300Dpi.webp&w=1080&q=80",
    title: "Colour Dial Carpet",
    price: "$2380",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2Fimage-thumb__14442__header_fullscreen_2x_jpg%2FMonster_Carpet_250.webp&w=1080&q=80",
    title: "Monster Carpet",
    price: "$2850",
    available: "In stock",
    type: "wallFloor",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCarpets%2FDropshadow%20Transparant%20Background%2F14398%2Fimage-thumb__14398__header_fullscreen_2x_jpg%2FFools%20Paradise%20Rug%20S160006.webp&w=3840&q=80",
    title: "Fools Paradise Carpet",
    price: "$2850",
    available: "In stock",
    type: "wallFloor",
  },
];
export let wallFloorHead = {
  name: "Wall & Floor",
  Btn: ["All Wall & Floor", "Wallcovering", "Carpets"],
};

export let wallFloorbottomArea = {
  p: "See more types of Wall & Floor",
  bottomBtn: ["Wallcovering", "Carpets"],
};
