export const lighting = [
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPallana%20Light%2Fimage-thumb__63859__header_fullscreen_2x_jpg%2FPallana-Light-Pebble.webp&w=3840&q=80",
    alt: "Pallana Light",
    title: "Pallana Light",
    price: "$3494",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FGravity%20Chandelier%2FGravity%20Chandelier%207%2Fimage-thumb__31489__header_fullscreen_2x_jpg%2FGravity-Chandelier-7-random.webp&w=3840&q=80",
    title: "Gravity Chandelier",
    price: "$1725",
    available: "in stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FRaimond%20II%2FRaimond%20II%20Suspension%2FRaimond%20II%20R61%2Fimage-thumb__34424__header_fullscreen_2x_jpg%2FRaimond-II-R61.webp&w=1080&q=80",
    alt: "Raimond IIs",
    title: "Raimond IIs",
    price: "$2281",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FRaimond%20II%2FRaimond%20II%20Suspension%2FRaimond%20II%20Dome%2Fimage-thumb__34414__header_fullscreen_2x_jpg%2FRaimond-II-Dome.webp&w=1080&q=80",
    title: "Raimond II Dome",
    price: "$3332",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FRaimond%20II%2FRaimond%20II%20Suspension%2FRaimond%20II%20R163%2Fimage-thumb__34459__header_fullscreen_2x_jpg%2FRaimond-II-R163.webp&w=1080&q=80",
    title: "Raimond II R127-R163-R199",
    price: "$18662",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FRaimond%20II%2FRaimond%20II%20Suspension%2FRaimond%20II%20Zafu%2Fimage-thumb__34444__header_fullscreen_2x_jpg%2FRaimond-II-Zafu.webp&w=1080&q=80",
    title: "Raimond II Zafu",
    price: "$4706",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FRaimond%20II%2FRaimond%20II%20Tensegrity%2FRaimond%20II%20Tensegrity%20Floor%20R61%2Fimage-thumb__34434__header_fullscreen_2x_jpg%2FRaimond-II-Tensegrity-R61.webp&w=1080&q=80",
    title: "Raimond II Tensegrity",
    price: "$6253",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPlie%20Plisse%20Light%2Fimage-thumb__38159__header_fullscreen_2x_jpg%2FPlie-Plisse-light-out-V2.jpg&w=1080&q=80",
    title: "Plié Plissé Light",
    price: "$979",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FChalice%2FChalice%2048%2F13140%2Fimage-thumb__13140__header_fullscreen_2x_jpg%2FChalice_Chrome-48-1.webp&w=1080&q=80",
    title: "Chalice",
    price: "$6450",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FFlock%20of%20Light%2FFlock%20of%20Light%2011%2Fimage-thumb__40083__header_fullscreen_2x_jpg%2FFlock-of-Light-11-V2.jpg&w=3840&q=80",
    title: "Flock of Light",
    price: "$727",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPerch%2FPerch%20Light%20Branch%2FPerch%20Light%20Branch%2F1857%2Fimage-thumb__1857__header_fullscreen_2x_jpg%2FPerch-Light-Branch.webp&w=3840&q=80",
    title: "Perch Light Branch",
    price: "$1395",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPerch%2FPerch%20Light%20Floor%2F1856%2Fimage-thumb__1856__header_fullscreen_2x_jpg%2FPerch-Light-Floor.webp&w=1080&q=80",
    title: "Perch Light Floor",
    price: "$1889",
    available: "Only 2 left in stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPerch%2FPerch%20Light%20Table%2F13822%2Fimage-thumb__13822__header_fullscreen_2x_jpg%2FPerch-Light-Table-8_swivel.webp&w=1080&q=80",
    title: "Perch Light Table",
    price: "$1604",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FPerch%2FPerch%20Light%20Tree%2F6270%2Fimage-thumb__6270__header_fullscreen_2x_jpg%2FPerch_Tree.webp&w=1080&q=80",
    title: "Perch Light Tree",
    price: "$33990",
    available: "Only 2 left in stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FSmoke%20Series%2FSmoke%20Chandelier%2F946%2Fimage-thumb__946__header_fullscreen_2x_jpg%2Fsmoke-chandelier-transparent.webp&w=3840&q=80",
    title: "Smoke Chandelier",
    price: "$1361",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FHeracleum%20III%2FLinear%2Fimage-thumb__49178__header_fullscreen_2x_jpg%2FHeracleum-III-Linear-WhiteV2.webp&w=3840&q=80",
    title: "Heracleum III Linear",
    price: "$4031",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FCoppelia%2FCoppelia%2F4031%2Fimage-thumb__4031__header_fullscreen_2x_jpg%2FCoppelia-2017feb-1.webp&w=3840&q=80",
    title: "Coppélia Suspended",
    price: "$3226",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FDear%20Ingo%2F2030%2Fimage-thumb__2030__header_fullscreen_2x_jpg%2Fdearingo-black-2.webp&w=3840&q=80",
    title: "Dear Ingo",
    price: "$3959",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FMeshmatics%2F14593%2Fimage-thumb__14593__header_fullscreen_2x_jpg%2FMeshmatics.webp&w=1080&q=80",
    title: "Meshmatics",
    price: "$2556",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNon%20Random%2FNon%20Random%20D71%2F1758%2Fimage-thumb__1758__header_fullscreen_2x_jpg%2Fnon-random-bl-on.webp&w=1080&q=80",
    title: "Non Random",
    price: "$747",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FNR2%2FNR2%20Suspenion%2FNR2%20Medium%2F1761%2Fimage-thumb__1761__header_fullscreen_2x_jpg%2FNR2-Medium-white1.webp&w=1080&q=80",
    title: "NR2",
    price: "$1361",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FThe%20Party%2FThe%20Party%20Wall%2FCoco%2Fimage-thumb__1953__header_fullscreen_2x_jpg%2FMoooi-The-Party-Coco-Light.webp&w=1080&q=80",
    title: "The Party Wall Lamp",
    price: "$575",
    available: "In stock",
    type: "lighting",
  },
  {
    src: "https://www.moooi.com/_next/image?url=https%3A%2F%2Fcdn.moooi.com%2Ftmp%2Fimage-thumbnails%2FCollection%2FValentine%2FValentine%20Table%2Fimage-thumb__13119__header_fullscreen_2x_jpg%2Fvalentine-table-lamp-black-portrait.webp&w=1080&q=80",
    title: "Valentine Table Lamp",
    price: "$1852",
    available: "Only 2 left in stock",
    type: "lighting",
  },
];
export let lightingHead = {
  name: "Ligthing",
  Btn: [
    "All Lighting",
    "Wall Lamps",
    "Floor Lamps",
    "Suspension Lamps",
    "Table Lamps",
    "Light Bulbs & Hardware",
  ],
};

export let lightingbottomArea = {
  p: "See more types of Lighting",
  bottomBtn: [
    "Wall Lamps",
    "Floor Lamps",
    "Suspension Lamps",
    "Table Lamps",
    "Light Bulbs & Hardware",
  ],
};
